### ISSUE TITLE
Method API not supported on this platform

### ISSUE THREAD

**Issue by pasevin** [apptentive/apptentive-trigger-io#5]
All Trigger.io native plugins need to update to support arm64 devices running ios8. At the moment Apptentive module is not up to date, and doesn't work on iPhone 5s/6/6+ running ios8.

**Comment by hussfelt** [comment]
Is this still an issue, and is this why I even after enabling everything see this:
```TypeError: undefined is not a function (evaluating 'forge.apptentive.showMessageCenterWithCustomData')```
